name: example
description: >
  Displays an About dialog, which describes the application,
  can show licenses, changelog, and other information.
version: 2.0.1
homepage: https://github.com/thorito/flutter_about
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  about:
  cupertino_icons:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  pubspec_extract:

dependency_overrides:
  about_custom:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - CHANGELOG.md
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.md
    - README.md

builders:
  about:
