name: about_custom
description: Displays an About dialog, which describes the application, can show licenses, changelog, and other information.
homepage: https://github.com/thorito/flutter_about
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.0
  markdown: ">=4.0.0 <6.0.0"
  path: ^1.8.2
  simple_mustache: ^2.1.0
  url_launcher: ">=6.0.0 <7.0.0"

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
