name: about_custom
description: Displays an About dialog, which describes the application, can show licenses, changelog, and other information.
homepage: https://github.com/thorito/flutter_about
version: 2.0.1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.14
  markdown: ^7.1.0
  path: ^1.8.3
  simple_mustache: ^2.1.0
  url_launcher: ">=6.0.0 <7.0.0"

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
